cd ~/projects/bloodcell_clip/vision/open_clip/scripts; conda activate med_instruct

export CUDA_VISIBLE_DEVICES='0'
torchrun \
    --nnodes=1 --nproc_per_node=1 --master_addr=localhost --master_port=2130 \
    -m main \
    --train-data="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/mgh/mgh_train_2403/shard_{0000..004}.tar"  \
    --val-data="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/mgh/mgh_val_2403/shard_{0000..0001}.tar"  \
    --train-num-samples 16000 \
    --val-num-samples 6400 \
    --dataset-type icddataset \
    --workers 2 \
    --batch-size 32 \
    --accum-freq 1 \
    --epochs 50 \
    --lr 5e-5 \
    --beta1 0.9 \
    --beta2 0.98 \
    --eps 1e-6 \
    --wd 0.1 \
    --grad-clip-norm 1.0 \
    --warmup 20 \
    --lr-scheduler cosine \
    --lr-cooldown-end 5e-6 \
    --coca-caption-loss-weight 1.0 \
    --coca-contrastive-loss-weight 0.0 \
    --precision amp \
    --save-frequency 1 \
    --val-frequency 1 \
    --zeroshot-frequency 0 \
    --local-loss \
    --gather-with-grad \
    --report-to wandb \
    --code-column phecode \
    --wandb-project-name="open-clip-phe-test-runs" \
    --encounter-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/all_encounters_2308_with_phecodes_with_na.parquet.check" \
    --demographic-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/demographics_2404.parquet" \
    --labs-folder="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/labs" \
    --time-difference-normalize 1 \
    --number-of-instructions 1 \
    --k-shot 1 \
    --k-shot-demographics 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --k-shot-labs 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --max_seq_length 64 \
    --pad_id 0 \
    --distance-threshold 60 \
    --negatives-type random \
    --tasks all \
    --task-shuffle \
    --fixed-position-range \
    --future-only \
    --seed 0 \
    --model ecg_scatter_global

export CUDA_VISIBLE_DEVICES='1'
torchrun \
    --nnodes=1 --nproc_per_node=1 --master_addr=localhost --master_port=2131 \
    -m main \
    --train-data="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/mgh/mgh_train_2403/shard_{0000..004}.tar"  \
    --val-data="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/mgh/mgh_val_2403/shard_{0000..0001}.tar"  \
    --train-num-samples 16000 \
    --val-num-samples 6400 \
    --dataset-type icddataset \
    --workers 2 \
    --batch-size 32 \
    --accum-freq 1 \
    --epochs 50 \
    --lr 5e-5 \
    --beta1 0.9 \
    --beta2 0.98 \
    --eps 1e-6 \
    --wd 0.1 \
    --grad-clip-norm 1.0 \
    --warmup 20 \
    --lr-scheduler cosine \
    --lr-cooldown-end 5e-6 \
    --coca-caption-loss-weight 1.0 \
    --coca-contrastive-loss-weight 0.0 \
    --precision amp \
    --save-frequency 1 \
    --val-frequency 1 \
    --zeroshot-frequency 0 \
    --local-loss \
    --gather-with-grad \
    --report-to wandb \
    --code-column phecode \
    --wandb-project-name="open-clip-phe-test-runs" \
    --encounter-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/all_encounters_2308_with_phecodes_with_na.parquet.check" \
    --demographic-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/demographics_2404.parquet" \
    --labs-folder="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/labs" \
    --time-difference-normalize 1 \
    --number-of-instructions 1 \
    --k-shot 1 \
    --k-shot-demographics 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --k-shot-labs 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --max_seq_length 64 \
    --pad_id 0 \
    --distance-threshold 60 \
    --negatives-type random \
    --tasks all \
    --task-shuffle \
    --fixed-position-range \
    --future-only \
    --seed 0 \
    --model ecg_cnn_windowed2


export CUDA_VISIBLE_DEVICES='2'
torchrun \
    --nnodes=1 --nproc_per_node=1 --master_addr=localhost --master_port=2132 \
    -m main \
    --train-data="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/mgh/mgh_train_2403/shard_{0000..004}.tar"  \
    --val-data="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/mgh/mgh_val_2403/shard_{0000..0001}.tar"  \
    --train-num-samples 16000 \
    --val-num-samples 6400 \
    --dataset-type icddataset \
    --workers 2 \
    --batch-size 32 \
    --accum-freq 1 \
    --epochs 50 \
    --lr 5e-5 \
    --beta1 0.9 \
    --beta2 0.98 \
    --eps 1e-6 \
    --wd 0.1 \
    --grad-clip-norm 1.0 \
    --warmup 20 \
    --lr-scheduler cosine \
    --lr-cooldown-end 5e-6 \
    --coca-caption-loss-weight 1.0 \
    --coca-contrastive-loss-weight 0.0 \
    --precision amp \
    --save-frequency 1 \
    --val-frequency 1 \
    --zeroshot-frequency 0 \
    --local-loss \
    --gather-with-grad \
    --report-to wandb \
    --code-column phecode \
    --wandb-project-name="open-clip-phe-test-runs" \
    --encounter-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/all_encounters_2308_with_phecodes_with_na.parquet.check" \
    --demographic-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/demographics_2404.parquet" \
    --labs-folder="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/labs" \
    --time-difference-normalize 1 \
    --number-of-instructions 1 \
    --k-shot 1 \
    --k-shot-demographics 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --k-shot-labs 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --max_seq_length 64 \
    --pad_id 0 \
    --distance-threshold 60 \
    --negatives-type random \
    --tasks all \
    --task-shuffle \
    --fixed-position-range \
    --future-only \
    --seed 0 \
    --model ecg_cnn_windowed1

export CUDA_VISIBLE_DEVICES='3'
torchrun \
    --nnodes=1 --nproc_per_node=1 --master_addr=localhost --master_port=2133 \
    -m main \
    --train-data="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/mgh/mgh_train_2403/shard_{0000..004}.tar"  \
    --val-data="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/mgh/mgh_val_2403/shard_{0000..0001}.tar"  \
    --train-num-samples 16000 \
    --val-num-samples 6400 \
    --dataset-type icddataset \
    --workers 2 \
    --batch-size 32 \
    --accum-freq 1 \
    --epochs 50 \
    --lr 5e-5 \
    --beta1 0.9 \
    --beta2 0.98 \
    --eps 1e-6 \
    --wd 0.1 \
    --grad-clip-norm 1.0 \
    --warmup 20 \
    --lr-scheduler cosine \
    --lr-cooldown-end 5e-6 \
    --coca-caption-loss-weight 1.0 \
    --coca-contrastive-loss-weight 0.0 \
    --precision amp \
    --save-frequency 1 \
    --val-frequency 1 \
    --zeroshot-frequency 0 \
    --local-loss \
    --gather-with-grad \
    --report-to wandb \
    --code-column phecode \
    --wandb-project-name="open-clip-phe-test-runs" \
    --encounter-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/all_encounters_2308_with_phecodes_with_na.parquet.check" \
    --demographic-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/demographics_2404.parquet" \
    --labs-folder="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/labs" \
    --time-difference-normalize 1 \
    --number-of-instructions 1 \
    --k-shot 1 \
    --k-shot-demographics 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --k-shot-labs 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --max_seq_length 64 \
    --pad_id 0 \
    --distance-threshold 60 \
    --negatives-type random \
    --tasks all \
    --task-shuffle \
    --fixed-position-range \
    --future-only \
    --seed 0 \
    --model ecg_cnn_windowed2

export CUDA_VISIBLE_DEVICES='4'
torchrun \
    --nnodes=1 --nproc_per_node=1 --master_addr=localhost --master_port=2134 \
    -m main \
    --train-data="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/mgh/mgh_train_2403/shard_{0000..004}.tar"  \
    --val-data="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/mgh/mgh_val_2403/shard_{0000..0001}.tar"  \
    --train-num-samples 16000 \
    --val-num-samples 6400 \
    --dataset-type icddataset \
    --workers 2 \
    --batch-size 32 \
    --accum-freq 1 \
    --epochs 50 \
    --lr 5e-5 \
    --beta1 0.9 \
    --beta2 0.98 \
    --eps 1e-6 \
    --wd 0.1 \
    --grad-clip-norm 1.0 \
    --warmup 20 \
    --lr-scheduler cosine \
    --lr-cooldown-end 5e-6 \
    --coca-caption-loss-weight 1.0 \
    --coca-contrastive-loss-weight 0.0 \
    --precision amp \
    --save-frequency 1 \
    --val-frequency 1 \
    --zeroshot-frequency 0 \
    --local-loss \
    --gather-with-grad \
    --report-to wandb \
    --code-column phecode \
    --wandb-project-name="open-clip-phe-test-runs" \
    --encounter-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/all_encounters_2308_with_phecodes_with_na.parquet.check" \
    --demographic-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/demographics_2404.parquet" \
    --labs-folder="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/labs" \
    --time-difference-normalize 1 \
    --number-of-instructions 1 \
    --k-shot 1 \
    --k-shot-demographics 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --k-shot-labs 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --max_seq_length 64 \
    --pad_id 0 \
    --distance-threshold 60 \
    --negatives-type random \
    --tasks all \
    --task-shuffle \
    --fixed-position-range \
    --future-only \
    --seed 0 \
    --model ecg_cnn_windowed3


## scattering
export CUDA_VISIBLE_DEVICES='5'
torchrun \
    --nnodes=1 --nproc_per_node=1 --master_addr=localhost --master_port=2135 \
    -m main \
    --train-data="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/mgh/mgh_train_2403/shard_{0000..004}.tar"  \
    --val-data="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/mgh/mgh_val_2403/shard_{0000..0001}.tar"  \
    --train-num-samples 16000 \
    --val-num-samples 6400 \
    --dataset-type icddataset \
    --workers 2 \
    --batch-size 32 \
    --accum-freq 1 \
    --epochs 50 \
    --lr 5e-5 \
    --beta1 0.9 \
    --beta2 0.98 \
    --eps 1e-6 \
    --wd 0.1 \
    --grad-clip-norm 1.0 \
    --warmup 20 \
    --lr-scheduler cosine \
    --lr-cooldown-end 5e-6 \
    --coca-caption-loss-weight 1.0 \
    --coca-contrastive-loss-weight 0.0 \
    --precision amp \
    --save-frequency 1 \
    --val-frequency 1 \
    --zeroshot-frequency 0 \
    --local-loss \
    --gather-with-grad \
    --report-to wandb \
    --code-column phecode \
    --wandb-project-name="open-clip-phe-test-runs" \
    --encounter-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/all_encounters_2308_with_phecodes_with_na.parquet.check" \
    --demographic-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/demographics_2404.parquet" \
    --labs-folder="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/labs" \
    --time-difference-normalize 1 \
    --number-of-instructions 1 \
    --k-shot 1 \
    --k-shot-demographics 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --k-shot-labs 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --max_seq_length 64 \
    --pad_id 0 \
    --distance-threshold 60 \
    --negatives-type random \
    --tasks all \
    --task-shuffle \
    --fixed-position-range \
    --future-only \
    --seed 0 \
    --model ecg_scatter_windowed


export CUDA_VISIBLE_DEVICES='6'
torchrun \
    --nnodes=1 --nproc_per_node=1 --master_addr=localhost --master_port=2136 \
    -m main \
    --train-data="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/mgh/mgh_train_2403/shard_{0000..004}.tar"  \
    --val-data="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/mgh/mgh_val_2403/shard_{0000..0001}.tar"  \
    --train-num-samples 16000 \
    --val-num-samples 6400 \
    --dataset-type icddataset \
    --workers 2 \
    --batch-size 32 \
    --accum-freq 1 \
    --epochs 50 \
    --lr 5e-5 \
    --beta1 0.9 \
    --beta2 0.98 \
    --eps 1e-6 \
    --wd 0.1 \
    --grad-clip-norm 1.0 \
    --warmup 20 \
    --lr-scheduler cosine \
    --lr-cooldown-end 5e-6 \
    --coca-caption-loss-weight 1.0 \
    --coca-contrastive-loss-weight 0.0 \
    --precision amp \
    --save-frequency 1 \
    --val-frequency 1 \
    --zeroshot-frequency 0 \
    --local-loss \
    --gather-with-grad \
    --report-to wandb \
    --code-column phecode \
    --wandb-project-name="open-clip-phe-test-runs" \
    --encounter-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/all_encounters_2308_with_phecodes_with_na.parquet.check" \
    --demographic-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/demographics_2404.parquet" \
    --labs-folder="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/labs" \
    --time-difference-normalize 1 \
    --number-of-instructions 1 \
    --k-shot 1 \
    --k-shot-demographics 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --k-shot-labs 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --max_seq_length 64 \
    --pad_id 0 \
    --distance-threshold 60 \
    --negatives-type random \
    --tasks all \
    --task-shuffle \
    --fixed-position-range \
    --future-only \
    --seed 0 \
    --model ecg_scatter_windowed2


export CUDA_VISIBLE_DEVICES='7'
torchrun \
    --nnodes=1 --nproc_per_node=1 --master_addr=localhost --master_port=2137 \
    -m main \
    --train-data="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/mgh/mgh_train_2403/shard_{0000..004}.tar"  \
    --val-data="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/mgh/mgh_val_2403/shard_{0000..0001}.tar"  \
    --train-num-samples 16000 \
    --val-num-samples 6400 \
    --dataset-type icddataset \
    --workers 2 \
    --batch-size 32 \
    --accum-freq 1 \
    --epochs 50 \
    --lr 5e-5 \
    --beta1 0.9 \
    --beta2 0.98 \
    --eps 1e-6 \
    --wd 0.1 \
    --grad-clip-norm 1.0 \
    --warmup 20 \
    --lr-scheduler cosine \
    --lr-cooldown-end 5e-6 \
    --coca-caption-loss-weight 1.0 \
    --coca-contrastive-loss-weight 0.0 \
    --precision amp \
    --save-frequency 1 \
    --val-frequency 1 \
    --zeroshot-frequency 0 \
    --local-loss \
    --gather-with-grad \
    --report-to wandb \
    --code-column phecode \
    --wandb-project-name="open-clip-phe-test-runs" \
    --encounter-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/all_encounters_2308_with_phecodes_with_na.parquet.check" \
    --demographic-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/demographics_2404.parquet" \
    --labs-folder="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/labs" \
    --time-difference-normalize 1 \
    --number-of-instructions 1 \
    --k-shot 1 \
    --k-shot-demographics 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --k-shot-labs 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --max_seq_length 64 \
    --pad_id 0 \
    --distance-threshold 60 \
    --negatives-type random \
    --tasks all \
    --task-shuffle \
    --fixed-position-range \
    --future-only \
    --seed 0 \
    --model ecg_scatter_windowed3



export CUDA_VISIBLE_DEVICES='1'
torchrun \
    --nnodes=1 --nproc_per_node=1 --master_addr=localhost --master_port=2131 \
    -m main \
    --train-data="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/mgh/mgh_train_2403/shard_{0000..004}.tar"  \
    --val-data="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/mgh/mgh_val_2403/shard_{0000..0001}.tar"  \
    --train-num-samples 16000 \
    --val-num-samples 6400 \
    --dataset-type icddataset \
    --workers 2 \
    --batch-size 32 \
    --accum-freq 2 \
    --epochs 50 \
    --lr 5e-5 \
    --beta1 0.9 \
    --beta2 0.98 \
    --eps 1e-6 \
    --wd 0.1 \
    --grad-clip-norm 1.0 \
    --warmup 20 \
    --lr-scheduler cosine \
    --lr-cooldown-end 5e-6 \
    --coca-caption-loss-weight 1.0 \
    --coca-contrastive-loss-weight 0.0 \
    --precision amp \
    --save-frequency 1 \
    --val-frequency 1 \
    --zeroshot-frequency 0 \
    --local-loss \
    --gather-with-grad \
    --report-to wandb \
    --code-column phecode \
    --wandb-project-name="open-clip-phe-test-runs" \
    --encounter-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/all_encounters_2308_with_phecodes_with_na.parquet.check" \
    --demographic-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/demographics_2404.parquet" \
    --labs-folder="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/labs" \
    --time-difference-normalize 1 \
    --number-of-instructions 1 \
    --k-shot 1 \
    --k-shot-demographics 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --k-shot-labs 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --max_seq_length 64 \
    --pad_id 0 \
    --distance-threshold 60 \
    --negatives-type random \
    --tasks diagnosis \
    --task-shuffle \
    --fixed-position-range \
    --future-only \
    --seed 0 \
    --model ecg_cnn_windowed2
 