# 1. Scratch - Diagnosis - Random - Fixed - Future
export CUDA_VISIBLE_DEVICES='0,1,2,3,4,5,6'
torchrun \
    --nnodes=1 --nproc_per_node=7 --master_addr=localhost --master_port=2120 \
    -m main \
    --train-data="/mnt/obi0/phi/ehr_projects/sysmex_datasets/processed_23-06-02/mgh_train_enc180d_v2/shard_{000..058}.tar"  \
    --val-data="/mnt/obi0/phi/ehr_projects/sysmex_datasets/processed_23-06-02/mgh_train_enc180d_v2/shard_{000..002}.tar"  \
    --train-num-samples 742400 \
    --val-num-samples 38400 \
    --dataset-type icddataset \
    --workers 8 \
    --batch-size 100 \
    --accum-freq 3 \
    --epochs 250 \
    --lr-scheduler cosine \
    --lr 2.5e-5 \
    --lr-cooldown-end 2.5e-6 \
    --beta1 0.9 \
    --beta2 0.999 \
    --eps 1e-8 \
    --wd 0.1 \
    --grad-clip-norm 1.0 \
    --warmup 30000 \
    --precision amp \
    --save-frequency 10 \
    --val-frequency 10 \
    --loss-function lm \
    --report-to wandb \
    --code-column phecode \
    --sample-result-date-column ResultDTS \
    --wandb-project-name="open-clip-phe-test-runs" \
    --encounter-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/all_encounters_2308_with_phecodes_with_na.parquet.check" \
    --demographic-file=/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/demographics_2404.parquet \
    --labs-folder=/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/labs \
    --time-difference-normalize 1 \
    --number-of-instructions 1 \
    --k-shot 1 \
    --max_seq_length 64 \
    --pad_id 1 \
    --add-img-token \
    --negatives-type random \
    --tasks diagnosis \
    --training-eval-codes MS_700.11 BI_170.1 ID_092.2 CA_121.1 \
    --fixed-position-range \
    --future-only \
    --name cyto_moca_scratch_diagnosis_k_1_random_fixed_future_250_trial_1 \
    --model cyto_moca_biogpt_scratch \
    --seed 0



# 2. Scratch - Labs - Demographics - Diagnosis - Random - Fixed - Past/Future - Multi
export CUDA_VISIBLE_DEVICES='0,1,2,3,4,5,6'
torchrun \
    --nnodes=1 --nproc_per_node=7 --master_addr=localhost --master_port=2120 \
    -m main \
    --train-data="/mnt/obi0/phi/ehr_projects/sysmex_datasets/processed_23-06-02/mgh_train_enc180d_v2/shard_{000..058}.tar"  \
    --val-data="/mnt/obi0/phi/ehr_projects/sysmex_datasets/processed_23-06-02/mgh_train_enc180d_v2/shard_{000..002}.tar"  \
    --train-num-samples 742400 \
    --val-num-samples 38400 \
    --dataset-type icddataset \
    --workers 8 \
    --batch-size 60 \
    --accum-freq 5 \
    --epochs 300 \
    --lr-scheduler cosine \
    --lr 2.5e-5 \
    --lr-cooldown-end 2.5e-6 \
    --beta1 0.9 \
    --beta2 0.999 \
    --eps 1e-8 \
    --wd 0.1 \
    --grad-clip-norm 1.0 \
    --warmup 35000 \
    --precision amp \
    --save-frequency 10 \
    --val-frequency 10 \
    --loss-function lm \
    --report-to wandb \
    --code-column phecode \
    --sample-result-date-column ResultDTS \
    --wandb-project-name="open-clip-phe-test-runs" \
    --encounter-file="/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/all_encounters_2308_with_phecodes_with_na.parquet.check" \
    --demographic-file=/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/demographics_2404.parquet \
    --labs-folder=/mnt/obi0/phi/ehr_projects/bloodcell_clip/data/cardiac/labs \
    --time-difference-normalize 1 \
    --number-of-instructions 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 \
    --k-shot 1 1 1 1 1 2 2 2 3 4 \
    --k-shot-demographics 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --k-shot-labs 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --k-shot-ecg-attributes 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 4 \
    --max_seq_length 196 \
    --pad_id 1 \
    --add-img-token \
    --negatives-type random \
    --tasks demographics diagnosis ecg_attributes labs \
    --task-shuffle \
    --training-eval-codes CV_424.4 EM_249 GU_627.2 NS_324.11 CV_416.214 \
    --fixed-position-range \
    --name cyto_moca_scratch_demographics_diagnosis_ecg_attributes_labs_random_fixed_multi_300_trial_1 \
    --model cyto_moca_biogpt_scratch \
    --seed 0